source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'WXDevtool', '0.15.1'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    pod 'WXLottie', :path=>'../../'
    pod 'WeexSDK'
    pod 'WeexPluginLoader'
    pod 'lottie-ios'
end

target 'WeexDemo' do
    common
end


